# Generated by Django 4.2.6 on 2023-10-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(verbose_name='Имя')),
                ('surnameName', models.TextField(verbose_name='Фамилия')),
                ('middleName', models.TextField(verbose_name='Очество')),
                ('old', models.IntegerField(verbose_name='Возраст')),
                ('birthDay', models.DateTimeField(verbose_name='День рождения')),
                ('professions', models.TextField(blank=True, verbose_name='Профессия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовки')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикован')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
