# Generated by Django 4.2.6 on 2023-10-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='middleName',
            field=models.TextField(verbose_name='Отчество'),
        ),
    ]
