# Generated by Django 4.2.6 on 2023-10-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('surnameName', models.TextField()),
                ('middleName', models.TextField()),
                ('old', models.IntegerField()),
                ('birthDay', models.DateTimeField()),
                ('professions', models.TextField(blank=True)),
            ],
        ),
    ]
