# Generated by Django 5.0.4 on 2024-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
    ]
